# Generated by Django 6.0.3 on 2026-03-31 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_taller_inscripciontaller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='tareas_asignadas',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='aprendizaje_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='2. ¿Qué te llevas de esta sesión?'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='focos_rojos',
            field=models.TextField(blank=True, null=True, verbose_name='🚨 Focos Rojos / Alertas'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='historia_clinica',
            field=models.TextField(blank=True, null=True, verbose_name='1. Cómo llega el paciente (Historia Clínica)'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='notas_alta',
            field=models.TextField(blank=True, null=True, verbose_name='3. Cómo se va (El Alta)'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='recomendaciones_generales',
            field=models.TextField(blank=True, null=True, verbose_name='4. Recomendaciones Generales'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AlterField(
            model_name='cuestionarioregistro',
            name='flujo_elegido',
            field=models.CharField(max_length=50, verbose_name='Tipo de Terapia'),
        ),
        migrations.AlterField(
            model_name='cuestionarioregistro',
            name='respuestas',
            field=models.JSONField(default=dict, verbose_name='Respuestas'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_clinica', to='core.cita'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='notas_sesion',
            field=models.TextField(verbose_name='Notas de la sesión'),
        ),
        migrations.DeleteModel(
            name='InscripcionTaller',
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
