# Generated by Django 6.0.3 on 2026-03-31 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_historialclinico_tareas_asignadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('descripcion', models.TextField(verbose_name='Descripción Breve')),
                ('tipo', models.CharField(choices=[('Taller', 'Taller de Bienestar'), ('Grupal', 'Terapia Grupal'), ('Padres', 'Escuela para Padres')], max_length=50, verbose_name='Categoría')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('cupo_maximo', models.PositiveIntegerField(default=20, verbose_name='Cupo Máximo')),
                ('enlace_meet', models.URLField(blank=True, null=True, verbose_name='Enlace de Google Meet para la sala grupal')),
                ('psicologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_impartidos', to='core.perfilpsicologo')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_inscritos', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.taller')),
            ],
            options={
                'unique_together': {('paciente', 'taller')},
            },
        ),
    ]
