# Generated by Django 6.0.3 on 2026-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_taller_inscripciontaller'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='como_llega',
            field=models.TextField(blank=True, null=True, verbose_name='1. ¿Cómo llega el paciente?'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='como_se_va',
            field=models.TextField(blank=True, null=True, verbose_name='4. Cierre y Alta de sesión'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True, verbose_name='5. Recomendaciones generales'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='aprendizaje_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='3. ¿Qué te llevas de esta sesión?'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='notas_sesion',
            field=models.TextField(verbose_name='2. Notas privadas del desarrollo'),
        ),
    ]
