# Generated by Django 6.0.3 on 2026-04-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historialclinico_como_llega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Logo principal, Foto doctores, etc.', max_length=100)),
                ('imagen', models.ImageField(upload_to='catalogo/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '2. Catálogo de Imagen',
                'verbose_name_plural': '2. Catálogo de Imágenes',
            },
        ),
        migrations.CreateModel(
            name='PaginaInicioHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_html', models.TextField(help_text='Pega aquí todo tu código. Usa las rutas del catálogo de imágenes para tus etiquetas <img>.', verbose_name='Código HTML Completo')),
            ],
            options={
                'verbose_name': '1. Editor de Código (Landing Page)',
                'verbose_name_plural': '1. Editor de Código (Landing Page)',
            },
        ),
    ]
