# Generated by Django 6.0.3 on 2026-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historialclinico_como_llega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='tipo',
            field=models.CharField(choices=[('Padres', 'Taller para Padres de Familia'), ('Pareja', 'Taller para Parejas'), ('Grupal', 'Taller Grupal'), ('Autoestima', 'Taller de Autoestima')], max_length=50, verbose_name='Categoría'),
        ),
    ]
