# Generated by Django 6.0.3 on 2026-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_taller_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='tipo',
            field=models.CharField(choices=[('padres', 'Taller para Padres de Familia'), ('pareja', 'Taller para Parejas'), ('grupal', 'Taller Grupal'), ('autoestima', 'Taller de Autoestima')], max_length=50, verbose_name='Categoría'),
        ),
    ]
