# Generated by Django 6.0.3 on 2026-04-25 06:17

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_catalogoimagen_paginainiciohtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoimagen',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('C:/Users/lemon/OneDrive/Escritorio/Poyectos/Oreocake-main/media')), upload_to='catalogo/'),
        ),
    ]
