# Generated by Django 6.0.3 on 2026-05-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_taller_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpsicologo',
            name='cv_breve',
            field=models.TextField(blank=True, null=True, verbose_name='Breve CV o Enfoque Clínico'),
        ),
        migrations.AddField(
            model_name='perfilpsicologo',
            name='foto',
            field=models.URLField(blank=True, max_length=800, null=True, verbose_name='Enlace de la Foto de Perfil'),
        ),
    ]
