# Generated by Django 6.0.3 on 2026-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfilpsicologo_cv_breve_perfilpsicologo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_doctores/', verbose_name='Foto de Perfil'),
        ),
    ]
