# Generated by Django 6.0.3 on 2026-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_perfilpsicologo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='bitacoras_adjuntos/', verbose_name='Documento Escaneado o Audio'),
        ),
    ]
