# Generated by Django 6.0.3 on 2026-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historialclinico_archivo_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='transcripcion_meet',
            field=models.FileField(blank=True, null=True, upload_to='transcripciones_meet/', verbose_name='Transcripción de Meet'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='bitacoras_adjuntos/', verbose_name='Documento Escaneado o Foto'),
        ),
    ]
