# Generated by Django 6.0.3 on 2026-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_historialclinico_transcripcion_meet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_evento_google',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
