# Generated by Django 6.0.3 on 2026-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cita_id_evento_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='modalidad',
            field=models.CharField(choices=[('En línea', 'En línea'), ('Presencial', 'Presencial')], default='En línea', max_length=50),
        ),
    ]
