# Generated by Django 6.0.3 on 2026-05-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cita_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='tipo',
            field=models.CharField(choices=[('padres', 'Taller para Padres de Familia'), ('pareja', 'Taller para Parejas'), ('grupal', 'Taller Grupal'), ('autoestima', 'Taller de Autoestima'), ('profesional', 'Eco-visión')], max_length=50, verbose_name='Categoría'),
        ),
    ]
