# Generated by Django 6.0.3 on 2026-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_taller_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_sesion',
            field=models.CharField(choices=[('individual', 'Individual'), ('pareja', 'En Pareja')], default='individual', max_length=50, verbose_name='Tipo de Sesión'),
        ),
    ]
