# Generated by Django 6.0.3 on 2026-06-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cita_tipo_sesion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('psicologo', 'fecha', 'hora')},
        ),
    ]
