# Generated by Django 6.0.3 on 2026-06-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_cita_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLibrePsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_libres', to='core.perfilpsicologo')),
            ],
            options={
                'unique_together': {('psicologo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='HorarioPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.perfilpsicologo')),
            ],
            options={
                'unique_together': {('psicologo', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
