# Generated by Django 6.0.3 on 2026-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_dialibrepsicologo_horariopsicologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialibrepsicologo',
            name='fecha',
            field=models.DateField(help_text='Para días libres extraoficiales (ej. vacaciones, enfermedad, permisos)'),
        ),
        migrations.DeleteModel(
            name='HorarioPsicologo',
        ),
    ]
