# Generated by Django 6.0.3 on 2026-06-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_dialibrepsicologo_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(blank=True, help_text='Usa el día 1 del mes', null=True)),
                ('semana', models.IntegerField(blank=True, choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4'), (5, 'Semana 5')], help_text='Semana del mes', null=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('es_descanso', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('hora_comida_inicio', models.TimeField(blank=True, null=True)),
                ('hora_comida_fin', models.TimeField(blank=True, null=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.perfilpsicologo')),
            ],
            options={
                'unique_together': {('psicologo', 'mes', 'semana', 'dia_semana')},
            },
        ),
    ]
