# Generated by Django 6.0.3 on 2026-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_horariopsicologo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioperfil',
            old_name='recomendaciones_generales',
            new_name='recommendaciones_generales',
        ),
        migrations.AddField(
            model_name='horariopsicologo',
            name='turno',
            field=models.CharField(blank=True, choices=[('matutino', 'Turno Matutino (8:00 am - 4:00 pm)'), ('vespertino', 'Turno Vespertino (1:00 pm - 9:00 pm)')], help_text='Selecciona el turno si trabaja este día', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dialibrepsicologo',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='es_descanso',
            field=models.BooleanField(default=False, verbose_name='¿Es día de Descanso?'),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='hora_comida_fin',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='hora_comida_inicio',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='hora_fin',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='hora_inicio',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='semana',
            field=models.IntegerField(blank=True, choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4'), (5, 'Semana 5')], null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='enlace_meet',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Google Meet'),
        ),
    ]
