# Generated by Django 6.0.3 on 2026-06-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_recomendaciones_generales_usuarioperfil_recommendaciones_generales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nuevos_pacientes_semana', models.PositiveIntegerField(default=0)),
                ('citas_completadas_mes', models.PositiveIntegerField(default=0)),
                ('citas_canceladas_mes', models.PositiveIntegerField(default=0)),
                ('talleres_activos', models.PositiveIntegerField(default=0)),
                ('focos_rojos_activos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalles', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_cita', 'Nueva cita agendada'), ('cancelacion', 'Cita cancelada'), ('foco_rojo', 'Foco rojo detectado'), ('recordatorio', 'Recordatorio')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_activadas', models.BooleanField(default=False)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
