# Generated by Django 6.0.3 on 2026-06-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_mensajechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPrensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título del Artículo')),
                ('slug', models.SlugField(help_text='URL amigable (ej: la-salud-mental-en-mexico)', max_length=250, unique=True)),
                ('resumen', models.TextField(help_text='Texto breve para la tarjeta de inicio')),
                ('contenido', models.TextField(help_text='Contenido completo del artículo (Soporta etiquetas HTML como <h3>, <p>, <ul>)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prensa/', verbose_name='Imagen de Portada')),
                ('imagen_url_externa', models.URLField(blank=True, help_text='O usa un enlace directo de Unsplash/Google', null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Mostrar en la página?')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
