# Generated by Django 6.0.3 on 2026-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_articuloprensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTallerPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('taller_seleccionado', models.CharField(max_length=200, verbose_name='Taller')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Taller',
                'verbose_name_plural': 'Registros de Talleres',
                'unique_together': {('correo', 'taller_seleccionado')},
            },
        ),
    ]
