# Generated by Django 6.0.3 on 2026-06-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_registrotallerpublico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
