# Generated by Django 6.0.3 on 2026-07-08 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_registrotallerpublico_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='integrantes_familia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de integrantes (Terapia Familiar)'),
        ),
        migrations.AddField(
            model_name='perfilpsicologo',
            name='atiende_familiar',
            field=models.BooleanField(default=False, verbose_name='Atiende Terapia Familiar'),
        ),
        migrations.AddField(
            model_name='perfilpsicologo',
            name='atiende_individual',
            field=models.BooleanField(default=True, verbose_name='Atiende Terapia Individual'),
        ),
        migrations.AddField(
            model_name='perfilpsicologo',
            name='atiende_pareja',
            field=models.BooleanField(default=False, verbose_name='Atiende Terapia de Pareja'),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='prensa/'),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='imagen_url_externa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='resumen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_sesion',
            field=models.CharField(choices=[('individual', 'Individual'), ('pareja', 'En Pareja'), ('familiar', 'Terapia Familiar')], default='individual', max_length=50),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='turno',
            field=models.CharField(blank=True, choices=[('matutino', 'Turno Matutino (8:00 am - 4:00 pm)'), ('vespertino', 'Turno Vespertino (1:00 pm - 9:00 pm)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificacionsistema',
            name='tipo',
            field=models.CharField(choices=[('nueva_cita', 'Nueva cita'), ('cancelacion', 'Cita cancelada'), ('foco_rojo', 'Foco rojo'), ('recordatorio', 'Recordatorio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='esta_activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aceptando nuevos pacientes'),
        ),
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], db_index=True, max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='taller_seleccionado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'estado'], name='core_cita_fecha_e3839f_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['psicologo', 'fecha', 'estado'], name='core_cita_psicolo_8df612_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilpsicologo',
            index=models.Index(fields=['esta_activo', 'genero'], name='core_perfil_esta_ac_e11225_idx'),
        ),
    ]
