# Generated by Django 6.0.3 on 2026-07-08 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_cita_integrantes_familia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoauditoria',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notificacionsistema',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='publicado',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='titulo',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Título del Artículo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], db_index=True, default='Confirmada', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha de la sesión'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_evento_google',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioregistro',
            name='fecha_completado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioregistro',
            name='flujo_elegido',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Terapia'),
        ),
        migrations.AlterField(
            model_name='dialibrepsicologo',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='accion',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], db_index=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='es_descanso',
            field=models.BooleanField(db_index=True, default=False, verbose_name='¿Es día de Descanso?'),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='mes',
            field=models.DateField(blank=True, db_index=True, help_text='Usa el día 1 del mes', null=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='semana',
            field=models.IntegerField(blank=True, choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4'), (5, 'Semana 5')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariopsicologo',
            name='turno',
            field=models.CharField(blank=True, choices=[('matutino', 'Turno Matutino (8:00 am - 4:00 pm)'), ('vespertino', 'Turno Vespertino (1:00 pm - 9:00 pm)')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscripciontaller',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora de envío'),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='leido',
            field=models.BooleanField(db_index=True, default=False, verbose_name='¿Fue leído?'),
        ),
        migrations.AlterField(
            model_name='notificacionsistema',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacionsistema',
            name='leida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificacionsistema',
            name='tipo',
            field=models.CharField(choices=[('nueva_cita', 'Nueva cita'), ('cancelacion', 'Cita cancelada'), ('foco_rojo', 'Foco rojo'), ('recordatorio', 'Recordatorio')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='atiende_familiar',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Atiende Terapia Familiar'),
        ),
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='atiende_individual',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Atiende Terapia Individual'),
        ),
        migrations.AlterField(
            model_name='perfilpsicologo',
            name='atiende_pareja',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Atiende Terapia de Pareja'),
        ),
        migrations.AlterField(
            model_name='preferenciasusuario',
            name='notificaciones_activadas',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='taller_seleccionado',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='telefono',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre del Programa'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='tipo',
            field=models.CharField(choices=[('padres', 'Taller para Padres de Familia'), ('pareja', 'Taller para Parejas'), ('grupal', 'Taller Grupal'), ('autoestima', 'Taller de Autoestima'), ('profesional', 'Eco-visión')], db_index=True, max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='es_psicologo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='telefono',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='articuloprensa',
            index=models.Index(fields=['publicado', 'fecha_publicacion'], name='core_articu_publica_95cc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'estado'], name='core_cita_pacient_d72ece_idx'),
        ),
        migrations.AddIndex(
            model_name='horariopsicologo',
            index=models.Index(fields=['psicologo', 'es_descanso'], name='core_horari_psicolo_546c67_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajechat',
            index=models.Index(fields=['destinatario', 'leido'], name='core_mensaj_destina_7e7713_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajechat',
            index=models.Index(fields=['destinatario', 'fecha_envio'], name='core_mensaj_destina_629190_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionsistema',
            index=models.Index(fields=['leida', 'fecha_creacion'], name='core_notifi_leida_40cc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilpsicologo',
            index=models.Index(fields=['esta_activo', 'atiende_individual'], name='core_perfil_esta_ac_b588f8_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilpsicologo',
            index=models.Index(fields=['esta_activo', 'atiende_pareja'], name='core_perfil_esta_ac_09bda4_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilpsicologo',
            index=models.Index(fields=['esta_activo', 'atiende_familiar'], name='core_perfil_esta_ac_9de1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotallerpublico',
            index=models.Index(fields=['taller_seleccionado', 'fecha_registro'], name='core_regist_taller__2dc685_idx'),
        ),
    ]
