# Generated by Django 6.0.3 on 2026-07-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_eventoauditoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mensajechat',
            name='core_mensaj_leido_f83e1e_idx',
        ),
        migrations.AlterField(
            model_name='articuloprensa',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
