# Generated by Django 6.0.3 on 2026-07-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_mensajechat_core_mensaj_leido_f83e1e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFijoPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('matutino', 'Turno Matutino (8:00 am - 4:00 pm)'), ('vespertino', 'Turno Vespertino (1:00 pm - 9:00 pm)')], max_length=20)),
                ('dia_descanso_1', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Primer día de descanso')),
                ('dia_descanso_2', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Segundo día de descanso')),
            ],
        ),


        migrations.AlterModelOptions(
            name='dialibrepsicologo',
            options={'verbose_name': 'Día Libre', 'verbose_name_plural': 'Días Libres'},
        ),
        migrations.AlterField(
            model_name='dialibrepsicologo',
            name='fecha',
            field=models.DateField(verbose_name='Día libre'),
        ),
        migrations.AlterField(
            model_name='dialibrepsicologo',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo (Opcional)'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='psicologo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_fijo', to='core.perfilpsicologo'),
        ),

    ]
