# Generated by Django 6.0.3 on 2026-07-09 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_horariofijopsicologo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariopsicologo',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='horariopsicologo',
            name='core_horari_psicolo_546c67_idx',
        ),
        migrations.AlterModelOptions(
            name='horariofijopsicologo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Horario Fijo', 'verbose_name_plural': 'Horarios Fijos'},
        ),
        migrations.RemoveField(
            model_name='horariofijopsicologo',
            name='dia_descanso_1',
        ),
        migrations.RemoveField(
            model_name='horariofijopsicologo',
            name='dia_descanso_2',
        ),
        migrations.RemoveField(
            model_name='horariofijopsicologo',
            name='turno',
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='dias_descanso',
            field=models.JSONField(default=list, help_text='Días de la semana en que el psicólogo NO atiende (ej. Lunes y Martes).', verbose_name='Días de descanso fijos'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='fecha_fin',
            field=models.DateField(blank=True, db_index=True, help_text='Si se deja en blanco, se calcula automáticamente a 3 meses de la fecha de inicio.', null=True, verbose_name='Vigente hasta (caducidad)'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='fecha_inicio',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Vigente desde'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='hora_comida_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Fin de comida'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='hora_comida_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio de comida'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin de jornada'),
        ),
        migrations.AddField(
            model_name='horariofijopsicologo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio de jornada'),
        ),
        migrations.AlterField(
            model_name='horariofijopsicologo',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fijos', to='core.perfilpsicologo', verbose_name='Psicólogo/a'),
        ),
        migrations.AddIndex(
            model_name='horariofijopsicologo',
            index=models.Index(fields=['psicologo', 'activo', 'fecha_inicio', 'fecha_fin'], name='core_horari_psicolo_da1970_idx'),
        ),
        migrations.DeleteModel(
            name='HorarioPsicologo',
        ),
    ]
