# Generated by Django 6.0.3 on 2026-07-10 01:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_horariopsicologo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_evento_google',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrotallerpublico',
            name='correo',
            field=models.EmailField(max_length=120),
        ),
        migrations.CreateModel(
            name='EsquemaHorarioPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField(verbose_name='Inicio Jornada')),
                ('hora_fin', models.TimeField(verbose_name='Fin Jornada')),
                ('hora_comida_inicio', models.TimeField(blank=True, null=True, verbose_name='Inicio Comida')),
                ('hora_comida_fin', models.TimeField(blank=True, null=True, verbose_name='Fin Comida')),
                ('dias_descanso', models.JSONField(default=list, help_text='Ej: [0, 1] para Lunes y Martes')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas_horarios', to='core.perfilpsicologo')),
            ],
            options={
                'verbose_name': 'Esquema de Horario',
                'verbose_name_plural': 'Esquemas de Horarios',
            },
        ),
    ]
