# Generated by Django 6.0.3 on 2026-07-10 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_cita_id_evento_google_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoVenezuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('celular', models.CharField(max_length=50, verbose_name='Número de celular')),
                ('lugar_vivienda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de vivienda')),
                ('horario_preferencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario de preferencia')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Contacto Venezuela',
                'verbose_name_plural': 'Contactos Venezuela',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
