# Generated by Django 6.0.3 on 2026-07-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_contactovenezuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPersonalizadoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Inicio jornada (este día)')),
                ('hora_fin', models.TimeField(verbose_name='Fin jornada (este día)')),
                ('hora_comida_inicio', models.TimeField(blank=True, null=True, verbose_name='Inicio comida')),
                ('hora_comida_fin', models.TimeField(blank=True, null=True, verbose_name='Fin comida')),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_personalizados', to='core.esquemahorariopsicologo')),
            ],
            options={
                'verbose_name': 'Horario personalizado por día',
                'verbose_name_plural': 'Horarios personalizados por día',
                'unique_together': {('esquema', 'dia_semana')},
            },
        ),
    ]
