# Generated by Django 6.0.3 on 2026-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_horariopersonalizadodia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariopersonalizadodia',
            options={'ordering': ['dia_semana', 'hora_inicio'], 'verbose_name': 'Bloque de horario personalizado', 'verbose_name_plural': 'Bloques de horario personalizado'},
        ),
        migrations.AlterUniqueTogether(
            name='horariopersonalizadodia',
            unique_together={('esquema', 'dia_semana', 'hora_inicio')},
        ),
        migrations.AddField(
            model_name='horariopersonalizadodia',
            name='tipo_sesion',
            field=models.CharField(choices=[('individual', 'Individual'), ('pareja', 'En Pareja'), ('familiar', 'Terapia Familiar')], default='individual', max_length=20, verbose_name='Tipo de sesión en este bloque'),
        ),
        migrations.AlterField(
            model_name='horariopersonalizadodia',
            name='hora_fin',
            field=models.TimeField(verbose_name='Fin del bloque'),
        ),
        migrations.AlterField(
            model_name='horariopersonalizadodia',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Inicio del bloque'),
        ),
        migrations.RemoveField(
            model_name='horariopersonalizadodia',
            name='hora_comida_fin',
        ),
        migrations.RemoveField(
            model_name='horariopersonalizadodia',
            name='hora_comida_inicio',
        ),
    ]
