# Generated by Django 6.0.3 on 2026-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_horariopersonalizadodia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpsicologo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono'),
        ),
    ]
