# Generated by Django 6.0.3 on 2026-07-25 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_perfilpsicologo_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaFormularioOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict, verbose_name='Respuestas del formulario')),
                ('puntaje', models.PositiveSmallIntegerField(default=0, verbose_name='Puntaje calculado')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario_organico', to='core.cita', verbose_name='Sesión (Cita)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario_organico', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Respuesta de Formulario Orgánico',
                'verbose_name_plural': 'Respuestas de Formulario Orgánico',
                'indexes': [models.Index(fields=['paciente', 'cita'], name='core_respue_pacient_21b502_idx')],
                'unique_together': {('paciente', 'cita')},
            },
        ),
    ]
