# Generated by Django 6.0.3 on 2026-08-13 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_respuestaformularioorganica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('colombia', 'Colombia'), ('venezuela', 'Venezuela'), ('otro', 'Otro')], db_index=True, max_length=30, verbose_name='País de origen')),
                ('form_type', models.CharField(choices=[('familia', 'Únete a nuestra familia'), ('donacion', 'Donación'), ('contacto', 'Contacto general')], db_index=True, default='familia', max_length=30, verbose_name='Tipo de formulario')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('celular', models.CharField(max_length=50, verbose_name='Número de celular')),
                ('lugar_vivienda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad / lugar de vivienda')),
                ('horario_preferencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario de preferencia')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje adicional')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Contacto por país',
                'verbose_name_plural': 'Contactos por país',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
