# Generated by Django 6.0.3 on 2026-08-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_contactopais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='reporte_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
