# Generated by Django 6.0.3 on 2026-09-06 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_cita_reporte_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('individual', 'Terapia Individual'), ('pareja', 'Terapia de Pareja'), ('familiar', 'Terapia Familiar')], db_index=True, max_length=20, verbose_name='Modalidad de Servicio')),
                ('historia_clinica', models.TextField(blank=True, null=True, verbose_name='1. Cómo llega el paciente (Historia Clínica de esta modalidad)')),
                ('focos_rojos', models.TextField(blank=True, null=True, verbose_name='🚨 Focos Rojos / Alertas')),
                ('recommendaciones_generales', models.TextField(blank=True, null=True, verbose_name='4. Recomendaciones Generales')),
                ('notas_alta', models.TextField(blank=True, null=True, verbose_name='3. Cómo se va (El Alta)')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Tratamiento Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tratamiento por Servicio',
                'verbose_name_plural': 'Tratamientos por Servicio',
            },
        ),
        migrations.AlterField(
            model_name='cuestionarioregistro',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cuestionarioregistro',
            index=models.Index(fields=['paciente', 'flujo_elegido'], name='core_cuesti_pacient_ed365f_idx'),
        ),
        migrations.AddIndex(
            model_name='cuestionarioregistro',
            index=models.Index(fields=['paciente', 'fecha_completado'], name='core_cuesti_pacient_c54a3e_idx'),
        ),
        migrations.AddField(
            model_name='tratamientopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='tratamientopaciente',
            name='psicologo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_asignados', to='core.perfilpsicologo', verbose_name='Psicólogo Asignado'),
        ),
        migrations.AddIndex(
            model_name='tratamientopaciente',
            index=models.Index(fields=['paciente', 'tipo_servicio'], name='core_tratam_pacient_cfbf47_idx'),
        ),
        migrations.AddIndex(
            model_name='tratamientopaciente',
            index=models.Index(fields=['psicologo_asignado', 'activo'], name='core_tratam_psicolo_d05f8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tratamientopaciente',
            unique_together={('paciente', 'tipo_servicio')},
        ),
    ]
