# Generated by Django 6.0.3 on 2026-09-07 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_tratamientopaciente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionSesionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('individual', 'Terapia Individual'), ('pareja', 'Terapia de Pareja'), ('familiar', 'Terapia Familiar')], default='individual', max_length=20, verbose_name='Modalidad de Servicio / Terapia')),
                ('respuestas_ipp', models.JSONField(default=dict, verbose_name='Respuestas del IPP')),
                ('puntaje_bruto_ipp', models.PositiveSmallIntegerField(default=0, verbose_name='Puntaje Bruto IPP (12-60)')),
                ('ipt', models.FloatField(default=0.0, verbose_name='Índice de Progreso Terapéutico IPT (0-100%)')),
                ('satisfaccion_atencion', models.PositiveSmallIntegerField(default=5, verbose_name='1. Satisfacción con la atención del terapeuta (1-5)')),
                ('sentirse_escuchado_respetado', models.PositiveSmallIntegerField(default=5, verbose_name='2. Sentirse escuchado, comprendido y respetado (1-5)')),
                ('avance_hacia_objetivos', models.PositiveSmallIntegerField(default=5, verbose_name='3. Avance hacia los objetivos de terapia (1-5)')),
                ('promedio_satisfaccion', models.FloatField(default=5.0, verbose_name='Promedio de Satisfacción (1-5)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales del paciente (opcional)')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_servicio', to='core.cita', verbose_name='Sesión / Cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_sesion', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='core.perfilpsicologo', verbose_name='Psicólogo que atendió')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_tratamiento', to='core.tratamientopaciente', verbose_name='Tratamiento del Paciente')),
            ],
            options={
                'verbose_name': 'Evaluación de Sesión del Paciente',
                'verbose_name_plural': 'Evaluaciones de Sesiones de Pacientes',
                'ordering': ['-fecha_respuesta'],
                'indexes': [models.Index(fields=['paciente', 'psicologo'], name='core_evalua_pacient_560c21_idx'), models.Index(fields=['tipo_proceso', 'fecha_respuesta'], name='core_evalua_tipo_pr_e21891_idx')],
            },
        ),
    ]
