# Generated by Django 6.0.3 on 2026-09-07 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_evaluacionsesionpaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteClinicoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_destinatario', models.CharField(choices=[('paciente', 'Versión Paciente (Check-in / Tareas / Progreso)'), ('psicologo', 'Versión Psicólogo (Expediente Clínico / Evolución)')], db_index=True, max_length=20, verbose_name='Tipo de Reporte')),
                ('numero_sesion', models.PositiveIntegerField(default=1, verbose_name='Número de sesión')),
                ('archivo_pdf', models.FileField(upload_to='reportes_sesiones/%Y/%m/', verbose_name='Archivo PDF generado')),
                ('datos_ia_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Resumen de datos clínicos e IA')),
                ('correo_enviado', models.BooleanField(default=False, verbose_name='¿Enviado por correo?')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de generación')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_pdf', to='core.cita', verbose_name='Cita asociada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_clinicos_pdf', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_emitidos_pdf', to='core.perfilpsicologo', verbose_name='Psicólogo tratante')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_pdf', to='core.tratamientopaciente', verbose_name='Tratamiento / Modalidad')),
            ],
            options={
                'verbose_name': 'Reporte Clínico en PDF',
                'verbose_name_plural': 'Reportes Clínicos en PDF',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['paciente', 'tipo_destinatario'], name='core_report_pacient_66be5c_idx'), models.Index(fields=['cita', 'tipo_destinatario'], name='core_report_cita_id_ab1dc3_idx')],
            },
        ),
    ]
