# Generated by Django 6.0.3 on 2026-09-09 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_reporteclinicopdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_firmante', models.CharField(max_length=200, verbose_name='Nombre del firmante')),
                ('acepta_telepsicologia', models.BooleanField(default=True, verbose_name='Acepta telepsicología')),
                ('declaracion_consentimiento', models.BooleanField(default=True, verbose_name='Declaración aceptada')),
                ('firma_base64', models.TextField(verbose_name='Firma en Base64')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='consentimientos/', verbose_name='Archivo PDF')),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de registro')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navegador o dispositivo')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora de firma')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión del documento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento Informado',
                'verbose_name_plural': 'Consentimientos Informados',
                'ordering': ['-fecha_firma'],
                'indexes': [models.Index(fields=['paciente', 'fecha_firma'], name='core_consen_pacient_77b888_idx')],
            },
        ),
    ]
