# Generated by Django 6.0.3 on 2026-09-10 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_consentimientoinformado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRepositorioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('consentimiento', 'Consentimiento informado'), ('pruebas_psicometricas', 'Pruebas psicométricas aplicadas'), ('ejercicios_sesion', 'Ejercicios realizados en sesiones'), ('tareas_consultante', 'Tareas entregadas por los consultantes'), ('notas_clinicas', 'Notas clínicas importantes del consultante'), ('procesos_procedimientos', 'Llenado de procesos y procedimientos (cuando aplique)'), ('otros', 'Otros')], db_index=True, max_length=50, verbose_name='Categoría del Documento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Documento o Nota')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción u Observaciones Clínicas')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='repositorio_clinico/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('contenido_extraido', models.TextField(blank=True, null=True, verbose_name='Texto Extraído para Búsqueda')),
                ('fecha_documento', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha del Documento')),
                ('es_institucional', models.BooleanField(db_index=True, default=False, verbose_name='¿Es formato/proceso institucional general?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_clinicos_repositorio', to=settings.AUTH_USER_MODEL, verbose_name='Consultante Asociado')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_repositorio', to='core.perfilpsicologo', verbose_name='Psicólogo Responsable')),
            ],
            options={
                'verbose_name': 'Documento del Repositorio Clínico',
                'verbose_name_plural': 'Documentos del Repositorio Clínico',
                'ordering': ['-fecha_documento', '-fecha_creacion'],
                'indexes': [models.Index(fields=['categoria', 'fecha_documento'], name='core_docume_categor_b76a73_idx'), models.Index(fields=['paciente', 'categoria'], name='core_docume_pacient_bd1111_idx'), models.Index(fields=['psicologo', 'categoria'], name='core_docume_psicolo_4e2e67_idx')],
            },
        ),
    ]
