# Generated by Django 6.0.3 on 2026-09-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_documentorepositorioclinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorepositorioclinico',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_repositorio', to='core.perfilpsicologo', verbose_name='Psicólogo Responsable'),
        ),
    ]
