# Generated by Django 6.0.3 on 2026-09-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_documentorepositorioclinico_psicologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('p1_hoy', models.CharField(max_length=80, verbose_name='1. Cómo te sientes hoy')),
                ('p2_emocion_semana', models.CharField(max_length=100, verbose_name='2. Emoción última semana')),
                ('p2_otra', models.CharField(blank=True, max_length=150, null=True, verbose_name='2. Otra emoción')),
                ('p3_saturacion', models.IntegerField(verbose_name='3. Nivel de saturación (0-10)')),
                ('p4_rebasado_accion', models.CharField(max_length=100, verbose_name='4. Acción al sentirse rebasado/a')),
                ('p4_otra', models.CharField(blank=True, max_length=150, null=True, verbose_name='4. Otra acción')),
                ('p5_dificultad', models.CharField(max_length=100, verbose_name='5. Dificultad dormir/concentrarse/disfrutar')),
                ('p6_acudir_ayuda', models.CharField(max_length=100, verbose_name='6. Sabrías con quién acudir')),
                ('p7_uso_ia_redes', models.CharField(max_length=100, verbose_name='7. Uso de IA / internet para entenderse')),
                ('p8_freno_ayuda', models.CharField(max_length=100, verbose_name='8. Freno para pedir ayuda profesional')),
                ('p8_otra', models.CharField(blank=True, max_length=150, null=True, verbose_name='8. Otro freno')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del votante')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
