# Generated by Django 6.0.3 on 2026-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_encuestarespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaFinalRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('palabra_id', models.CharField(max_length=50, verbose_name='ID de la acción/palabra')),
                ('palabra_label', models.CharField(max_length=150, verbose_name='Acción concreta elegida')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del votante')),
            ],
            options={
                'verbose_name': 'Respuesta Encuesta Final (Nube de Palabras)',
                'verbose_name_plural': 'Respuestas Encuesta Final (Nube de Palabras)',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
