# Generated by Django 6.0.3 on 2026-09-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_encuestafinalrespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='es_tectum',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cita Convenio TECTUM'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='es_tectum',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Convenio TECTUM In-House'),
        ),
    ]
