# Generated by Django 6.0.3 on 2026-10-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_es_tectum_mysql_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaTectum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo del colaborador')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('empresa', models.CharField(default='TECTUM In-House', max_length=150, verbose_name='Empresa')),
                ('area_departamento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área o Departamento')),
                ('puesto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Puesto')),
                ('respuestas', models.JSONField(default=dict, verbose_name='Respuestas del cuestionario (30 preguntas)')),
                ('puntuacion_total', models.IntegerField(default=0, verbose_name='Puntuación total (GHQ)')),
                ('nivel_riesgo', models.CharField(default='Normal / Favorable', max_length=50, verbose_name='Nivel de riesgo detectado')),
                ('alerta_critica', models.BooleanField(default=False, verbose_name='Alerta crítica (ideación/riesgo)')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de realización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_tectum', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrado (opcional)')),
            ],
            options={
                'verbose_name': 'Encuesta de Salud Mental TECTUM',
                'verbose_name_plural': 'Encuestas de Salud Mental TECTUM',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
